use super::{RuleSpec, ThresholdValue};

pub(super) const PY_RULE_SPECS: &[RuleSpec] = &[
    RuleSpec {
        metric: "statements_per_function",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.statements_per_function),
        description: "statements_per_function is the maximum number of statements in a Python function/method body.",
    },
    RuleSpec {
        metric: "positional_args",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.arguments_positional),
        description: "positional_args is the maximum number of positional parameters in a Python function definition.",
    },
    RuleSpec {
        metric: "keyword_only_args",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.arguments_keyword_only),
        description: "keyword_only_args is the maximum number of keyword-only parameters in a Python function definition.",
    },
    RuleSpec {
        metric: "max_indentation_depth",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.max_indentation_depth),
        description: "max_indentation_depth is the maximum indentation depth within a Python function/method body.",
    },
    RuleSpec {
        metric: "branches_per_function",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.branches_per_function),
        description: "branches_per_function is the number of if/elif/case_clause branches in a Python function.",
    },
    RuleSpec {
        metric: "local_variables_per_function",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.local_variables_per_function),
        description: "local_variables_per_function is the number of distinct local variables assigned in a Python function.",
    },
    RuleSpec {
        metric: "returns_per_function",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.returns_per_function),
        description: "returns_per_function is the number of return statements in a Python function.",
    },
    RuleSpec {
        metric: "return_values_per_function",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.return_values_per_function),
        description: "return_values_per_function is the maximum number of values returned by a single return statement in a Python function.",
    },
    RuleSpec {
        metric: "nested_function_depth",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.nested_function_depth),
        description: "nested_function_depth is the maximum nesting depth of function definitions inside a Python function.",
    },
    RuleSpec {
        metric: "statements_per_try_block",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.statements_per_try_block),
        description: "statements_per_try_block is the maximum number of statements inside any try block in a Python function.",
    },
    RuleSpec {
        metric: "boolean_parameters",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.boolean_parameters),
        description: "boolean_parameters is the maximum number of boolean default parameters (True/False) in a Python function.",
    },
    RuleSpec {
        metric: "annotations_per_function",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.annotations_per_function),
        description: "annotations_per_function counts Python decorators on a function; TOML key under [python] is decorators_per_function (maps to the same field).",
    },
    RuleSpec {
        metric: "calls_per_function",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.calls_per_function),
        description: "calls_per_function is the maximum number of function/method calls in a Python function.",
    },
    RuleSpec {
        metric: "methods_per_class",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.methods_per_class),
        description: "methods_per_class is the maximum number of methods defined on a Python class.",
    },
    RuleSpec {
        metric: "statements_per_file",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.statements_per_file),
        description: "statements_per_file is the maximum number of statements inside function/method bodies in a Python file.",
    },
    RuleSpec {
        metric: "lines_per_file",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.lines_per_file),
        description: "lines_per_file is the maximum number of source lines in a Python file (including comments and blanks).",
    },
    RuleSpec {
        metric: "functions_per_file",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.functions_per_file),
        description: "functions_per_file is the maximum number of functions/methods defined in a Python file.",
    },
    RuleSpec {
        metric: "interface_types_per_file",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.interface_types_per_file),
        description: "interface_types_per_file is the maximum number of interface types (Protocol/ABC classes) defined in a Python file.",
    },
    RuleSpec {
        metric: "concrete_types_per_file",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.concrete_types_per_file),
        description: "concrete_types_per_file is the maximum number of concrete types (non-Protocol/ABC classes) defined in a Python file.",
    },
    RuleSpec {
        metric: "imported_names_per_file",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.imported_names_per_file),
        description: "imported_names_per_file is the maximum number of unique imported names in a Python file (excluding TYPE_CHECKING-only imports).",
    },
    RuleSpec {
        metric: "cycle_size",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.cycle_size),
        description: "cycle_size is the maximum allowed number of modules participating in an import cycle.",
    },
    RuleSpec {
        metric: "indirect_dependencies",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.indirect_dependencies),
        description: "indirect_dependencies is the number of modules reachable only through other modules (total reachable minus direct fan-out).",
    },
    RuleSpec {
        metric: "dependency_depth",
        op: "<",
        threshold: ThresholdValue::Usize(|c, _| c.dependency_depth),
        description: "dependency_depth is the maximum length of an import chain in the dependency graph.",
    },
    RuleSpec {
        metric: "test_coverage_threshold",
        op: ">=",
        threshold: ThresholdValue::Usize(|_, g| g.test_coverage_threshold),
        description: "test_coverage_threshold is the minimum percent of code units per file whose names must appear in a test file (static check).",
    },
    RuleSpec {
        metric: "min_similarity",
        op: ">=",
        threshold: ThresholdValue::F64(|_, g| g.min_similarity),
        description: "min_similarity is the minimum similarity required to report duplicate code (when duplication_enabled=true).",
    },
];
