use super::types::{Applicability, Rule, RuleCategory};

pub static RULES: &[Rule] = &[
    Rule {
        category: RuleCategory::Functions,
        template: "Keep functions ≤ {} statements",
        get_threshold: |c, _| c.statements_per_function,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Use ≤ {} positional arguments; prefer keyword-only args after that",
        get_threshold: |c, _| c.arguments_positional,
        applicability: Applicability::Python,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Limit keyword-only arguments to ≤ {}",
        get_threshold: |c, _| c.arguments_keyword_only,
        applicability: Applicability::Python,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Limit arguments to ≤ {}",
        get_threshold: |c, _| c.arguments_per_function,
        applicability: Applicability::Rust,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Keep indentation depth ≤ {} levels",
        get_threshold: |c, _| c.max_indentation_depth,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Limit branches to ≤ {} per function",
        get_threshold: |c, _| c.branches_per_function,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Keep local variables ≤ {} per function",
        get_threshold: |c, _| c.local_variables_per_function,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Limit return statements to ≤ {} per function",
        get_threshold: |c, _| c.returns_per_function,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Return ≤ {} values per return statement",
        get_threshold: |c, _| c.return_values_per_function,
        applicability: Applicability::Python,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Avoid deeply nested functions/closures (max depth: {})",
        get_threshold: |c, _| c.nested_function_depth,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Keep try blocks narrow (≤ {} statements)",
        get_threshold: |c, _| c.statements_per_try_block,
        applicability: Applicability::Python,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Limit boolean parameters to ≤ {} per function",
        get_threshold: |c, _| c.boolean_parameters,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Use ≤ {} decorators per function",
        get_threshold: |c, _| c.annotations_per_function,
        applicability: Applicability::Python,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Use ≤ {} attributes per function",
        get_threshold: |c, _| c.annotations_per_function,
        applicability: Applicability::Rust,
    },
    Rule {
        category: RuleCategory::Functions,
        template: "Keep calls per function ≤ {}",
        get_threshold: |c, _| c.calls_per_function,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Classes,
        template: "Keep methods per class/type ≤ {}",
        get_threshold: |c, _| c.methods_per_class,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Files,
        template: "Keep files ≤ {} statements",
        get_threshold: |c, _| c.statements_per_file,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Files,
        template: "Keep files ≤ {} lines",
        get_threshold: |c, _| c.lines_per_file,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Files,
        template: "Keep files ≤ {} functions",
        get_threshold: |c, _| c.functions_per_file,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Files,
        template: "Limit to ≤ {} interface types (traits/ABCs) per file",
        get_threshold: |c, _| c.interface_types_per_file,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Files,
        template: "Limit to ≤ {} concrete types per file",
        get_threshold: |c, _| c.concrete_types_per_file,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Files,
        template: "Keep imported names ≤ {} per file",
        get_threshold: |c, _| c.imported_names_per_file,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Dependencies,
        template: "Avoid circular dependencies",
        get_threshold: |_, _| 0,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Dependencies,
        template: "Keep cycles small (≤ {} modules)",
        get_threshold: |c, _| c.cycle_size,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Dependencies,
        template: "Limit indirect dependencies to ≤ {}",
        get_threshold: |c, _| c.indirect_dependencies,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Dependencies,
        template: "Keep dependency depth ≤ {}",
        get_threshold: |c, _| c.dependency_depth,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Testing,
        template: "Every function/class/type should be mentioned in a test file",
        get_threshold: |_, _| 0,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Testing,
        template: "Maintain ≥ {}% test reference coverage (static check: name must appear in a test file)",
        get_threshold: |_, g| g.test_coverage_threshold,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Duplication,
        template: "Avoid copy-pasted code blocks",
        get_threshold: |_, _| 0,
        applicability: Applicability::Both,
    },
    Rule {
        category: RuleCategory::Duplication,
        template: "Factor out repeated patterns into shared functions",
        get_threshold: |_, _| 0,
        applicability: Applicability::Both,
    },
];
