use tempfile::TempDir;

use crate::discovery::Language;
use crate::gate_config::GateConfig;
use crate::stats::{MetricStats, PercentileSummary};

use super::config_keys::common_config_key;
use super::defaults_append::{append_python_defaults, append_rust_defaults};
use super::generate::{GenerateConfigParams, append_section, generate_config_toml_by_language};
use super::infer_gate::infer_gate_config_for_paths;
use super::merge::{MergeLanguageUpdate, build_merged_output, format_section, merge_config_toml};
use super::{python_config_key, rust_config_key, write_mimic_config};
use crate::config_gen::{
    collect_all_stats, collect_all_stats_with_ignore, collect_py_stats,
    collect_py_stats_with_ignore, collect_rs_stats, collect_rs_stats_with_ignore,
};

#[test]
fn test_collection() {
    let tmp = TempDir::new().unwrap();
    assert_eq!(collect_py_stats(tmp.path()).1, 0);
    assert_eq!(collect_rs_stats(tmp.path()).1, 0);
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    assert_eq!(collect_all_stats(&paths, None).0.1, 0);
    assert_eq!(
        collect_py_stats_with_ignore(tmp.path(), &["fake_".into()]).1,
        0
    );
    assert_eq!(
        collect_rs_stats_with_ignore(tmp.path(), &["fake_".into()]).1,
        0
    );
    assert_eq!(
        collect_all_stats_with_ignore(&paths, None, &["fake_".into()])
            .0
            .1,
        0
    );
}

#[test]
fn test_config_keys() {
    assert_eq!(
        python_config_key("statements_per_function"),
        Some("statements_per_function")
    );
    assert_eq!(
        rust_config_key("statements_per_function"),
        Some("statements_per_function")
    );
    assert_eq!(
        python_config_key("statements_per_file"),
        Some("statements_per_file")
    );
    assert_eq!(
        common_config_key("branches_per_function"),
        Some("branches_per_function")
    );
}

#[test]
fn test_config_generation() {
    let gate = GateConfig::default();
    assert!(
        generate_config_toml_by_language(&GenerateConfigParams {
            py: &MetricStats::default(),
            rs: &MetricStats::default(),
            py_n: 0,
            rs_n: 0,
            py_graph: crate::GraphKeyMaxima::default(),
            rs_graph: crate::GraphKeyMaxima::default(),
            gate: &gate,
        })
        .contains("Generated by kiss")
    );
    assert!(build_merged_output(&toml::Table::new()).contains("Generated by kiss"));
    let mut out = String::new();
    let mut table = toml::Table::new();
    table.insert("key".into(), toml::Value::Integer(42));
    format_section(&mut out, "test", Some(&toml::Value::Table(table)));
    assert!(out.contains("[test]") && out.contains("key = 42"));
    let mut out2 = String::new();
    append_section(
        &mut out2,
        "[python]",
        &[PercentileSummary {
            metric_id: "statements_per_function",
            count: 10,
            max: 50,
            p50: 5,
            p90: 10,
            p95: 15,
            p99: 20,
        }],
        python_config_key,
    );
    assert!(out2.contains("statements_per_function = 50"));
}

#[test]
fn test_defaults_appenders() {
    let mut py_full = String::new();
    append_python_defaults(&mut py_full);
    assert!(py_full.contains("[python]") && py_full.contains("statements_per_function"));
    let mut rs_full = String::new();
    append_rust_defaults(&mut rs_full);
    assert!(rs_full.contains("[rust]") && rs_full.contains("arguments"));
}

#[test]
fn test_infer_gate_keeps_default_coverage_threshold() {
    let tmp = TempDir::new().unwrap();
    std::fs::write(
        tmp.path().join("app.py"),
        "def covered():\n    return 1\n\ndef uncovered():\n    return 2\n",
    )
    .unwrap();
    std::fs::write(
        tmp.path().join("test_app.py"),
        "from app import covered\n\ndef test_covered():\n    assert covered() == 1\n",
    )
    .unwrap();
    std::fs::write(
        tmp.path().join("fake_extra.py"),
        "def ignored_uncovered():\n    return 3\n",
    )
    .unwrap();

    let paths = vec![tmp.path().to_string_lossy().to_string()];
    let ignore = vec!["fake_".to_string()];
    let gate = infer_gate_config_for_paths(&paths, None, &ignore);
    assert_eq!(
        gate.test_coverage_threshold,
        GateConfig::default().test_coverage_threshold,
        "mimic/clamp must not infer coverage from static references"
    );
}

#[test]
fn test_infer_gate_config_orphan_module_enabled() {
    let tmp = TempDir::new().unwrap();
    let orphan_py = tmp.path().join("orphan.py");
    std::fs::write(&orphan_py, "def foo():\n    pass\n").unwrap();
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    let gate = infer_gate_config_for_paths(&paths, Some(Language::Python), &[]);
    assert!(
        !gate.orphan_module_enabled,
        "orphan module should set orphan_module_enabled=false"
    );
}

#[test]
fn test_infer_gate_config_no_orphans_module_enabled() {
    let tmp = TempDir::new().unwrap();
    let a_py = tmp.path().join("a.py");
    let b_py = tmp.path().join("b.py");
    std::fs::write(&a_py, "from b import bar\ndef foo():\n    bar()\n").unwrap();
    std::fs::write(&b_py, "def bar():\n    pass\n").unwrap();
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    let gate = infer_gate_config_for_paths(&paths, Some(Language::Python), &[]);
    assert!(
        gate.orphan_module_enabled,
        "no orphan modules should set orphan_module_enabled=true"
    );
}

#[test]
fn test_infer_gate_config_comment_removal_enabled() {
    let tmp = TempDir::new().unwrap();
    std::fs::write(
        tmp.path().join("a.py"),
        "from b import bar\ndef foo():\n    bar()\n",
    )
    .unwrap();
    std::fs::write(tmp.path().join("b.py"), "def bar():\n    pass\n").unwrap();
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    let gate = infer_gate_config_for_paths(&paths, Some(Language::Python), &[]);
    assert!(
        gate.comment_removal_enabled,
        "comment-free python should enable comment_removal"
    );

    let tmp2 = TempDir::new().unwrap();
    std::fs::write(
        tmp2.path().join("noted.py"),
        "# keep this\ndef foo():\n    return 1\n",
    )
    .unwrap();
    let paths2 = vec![tmp2.path().to_string_lossy().to_string()];
    let gated = infer_gate_config_for_paths(&paths2, Some(Language::Python), &[]);
    assert!(
        !gated.comment_removal_enabled,
        "comments should set comment_removal_enabled=false"
    );
}
#[test]
fn test_write_mimic_config_smoke() {
    let tmp = tempfile::tempdir().unwrap();
    let out = tmp.path().join("mimic_out.toml");
    let toml = "[test]\ntest_coverage_threshold = 90\n";
    write_mimic_config(&out, toml, 0, 0).unwrap();
    assert!(out.exists());
}

#[test]
fn test_merge_config_toml_smoke() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(&path, "[python]\nstatements_per_function = 1\n").unwrap();
    let merged = merge_config_toml(
        &path,
        "[python]\nstatements_per_function = 2\n[rust]\narguments = 4\n",
        MergeLanguageUpdate::Both,
    );
    assert!(merged.contains("statements_per_function"));
}

#[test]
fn merge_omits_unanalyzed_language_table() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(
        &path,
        "[python]\nstatements_per_function = 1\n[rust]\narguments = 8\n",
    )
    .unwrap();
    let merged = merge_config_toml(
        &path,
        "[python]\nstatements_per_function = 2\n",
        MergeLanguageUpdate::PythonOnly,
    );
    assert!(merged.contains("[python]"), "{merged}");
    assert!(
        !merged.contains("[rust]"),
        "unanalyzed rust table must be omitted:\n{merged}"
    );
}

#[test]
fn merge_keeps_existing_test_section() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(
        &path,
        "[python]\nstatements_per_function = 1\n[test]\nnum_jobs = 8\npytest_plugins = [\"x\"]\nignore = [\"vendor\"]\n",
    )
    .unwrap();
    let merged = merge_config_toml(
        &path,
        "[python]\nstatements_per_function = 2\n[test]\nnum_jobs = 4\npytest_plugins = []\nignore = []\n",
        MergeLanguageUpdate::PythonOnly,
    );
    assert!(
        merged.contains("[test]"),
        "merged output must include [test]:\n{merged}"
    );
    assert!(
        merged.contains("num_jobs = 8"),
        "existing num_jobs must be preserved:\n{merged}"
    );
    assert!(
        merged.contains("pytest_plugins = [\"x\"]"),
        "existing pytest_plugins must be preserved:\n{merged}"
    );
    assert!(
        merged.contains("ignore = [\"vendor\"]"),
        "existing ignore must be preserved:\n{merged}"
    );
}

#[test]
fn merge_adds_test_section_from_new_when_missing() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(&path, "[python]\nstatements_per_function = 1\n").unwrap();
    let merged = merge_config_toml(
        &path,
        "[python]\nstatements_per_function = 2\n[test]\nnum_jobs = 4\nwatch_settle_seconds = 1.0\npytest_plugins = []\nignore = []\n",
        MergeLanguageUpdate::PythonOnly,
    );
    assert!(
        merged.contains("[test]"),
        "merged output must include [test]:\n{merged}"
    );
    assert!(
        merged.contains("num_jobs = 4"),
        "new num_jobs default must be present:\n{merged}"
    );
    assert!(
        merged.contains("pytest_plugins = []"),
        "new pytest_plugins default must be present:\n{merged}"
    );
    assert!(
        merged.contains("ignore = []"),
        "new ignore default must be present:\n{merged}"
    );
}
