use tempfile::TempDir;

use crate::discovery::Language;
use crate::gate_config::GateConfig;
use crate::stats::{MetricStats, PercentileSummary};

use super::collect::{
    collect_all_stats, collect_all_stats_with_ignore, collect_py_stats,
    collect_py_stats_with_ignore, collect_rs_stats, collect_rs_stats_with_ignore,
};
use super::config_keys::common_config_key;
use super::defaults_append::{append_python_defaults, append_rust_defaults};
use super::generate::{GenerateConfigParams, append_section, generate_config_toml_by_language};
use super::infer_gate::infer_gate_config_for_paths;
use super::merge::{MergeLanguageUpdate, build_merged_output, format_section, merge_config_toml};
use super::{python_config_key, rust_config_key, write_mimic_config};

#[test]
fn test_collection() {
    let tmp = TempDir::new().unwrap();
    assert_eq!(collect_py_stats(tmp.path()).1, 0);
    assert_eq!(collect_rs_stats(tmp.path()).1, 0);
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    assert_eq!(collect_all_stats(&paths, None).0.1, 0);
    assert_eq!(
        collect_py_stats_with_ignore(tmp.path(), &["fake_".into()]).1,
        0
    );
    assert_eq!(
        collect_rs_stats_with_ignore(tmp.path(), &["fake_".into()]).1,
        0
    );
    assert_eq!(
        collect_all_stats_with_ignore(&paths, None, &["fake_".into()])
            .0
            .1,
        0
    );
}

#[test]
fn test_config_keys() {
    assert_eq!(
        python_config_key("statements_per_function"),
        Some("statements_per_function")
    );
    assert_eq!(
        rust_config_key("statements_per_function"),
        Some("statements_per_function")
    );
    assert_eq!(
        python_config_key("statements_per_file"),
        Some("statements_per_file")
    );
    assert_eq!(
        common_config_key("branches_per_function"),
        Some("branches_per_function")
    );
}

#[test]
fn test_config_generation() {
    let gate = GateConfig::default();
    assert!(
        generate_config_toml_by_language(&GenerateConfigParams {
            py: &MetricStats::default(),
            rs: &MetricStats::default(),
            py_n: 0,
            rs_n: 0,
            gate: &gate,
        })
        .contains("Generated by kiss")
    );
    assert!(build_merged_output(&toml::Table::new()).contains("Generated by kiss"));
    let mut out = String::new();
    let mut table = toml::Table::new();
    table.insert("key".into(), toml::Value::Integer(42));
    format_section(&mut out, "test", Some(&toml::Value::Table(table)));
    assert!(out.contains("[test]") && out.contains("key = 42"));
    let mut out2 = String::new();
    append_section(
        &mut out2,
        "[python]",
        &[PercentileSummary {
            metric_id: "statements_per_function",
            count: 10,
            max: 50,
            p50: 5,
            p90: 10,
            p95: 15,
            p99: 20,
        }],
        python_config_key,
    );
    assert!(out2.contains("statements_per_function = 50"));
}

#[test]
fn test_defaults_appenders() {
    let mut py_full = String::new();
    append_python_defaults(&mut py_full);
    assert!(py_full.contains("[python]") && py_full.contains("statements_per_function"));
    let mut rs_full = String::new();
    append_rust_defaults(&mut rs_full);
    assert!(rs_full.contains("[rust]") && rs_full.contains("arguments"));
}

#[test]
fn test_infer_gate_threshold_matches_direct_floor_for_fixture() {
    let tmp = TempDir::new().unwrap();
    std::fs::write(
        tmp.path().join("module.py"),
        "def uncovered():\n    return 1\n",
    )
    .unwrap();
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    let ignore = Vec::new();
    let (py_files, rs_files) = crate::discovery::gather_files_by_lang(&paths, None, &ignore);
    let py_parsed: Vec<_> = crate::parsing::parse_files(&py_files)
        .unwrap()
        .into_iter()
        .filter_map(Result::ok)
        .collect();
    let rs_parsed: Vec<_> = crate::rust_parsing::parse_rust_files(&rs_files)
        .into_iter()
        .filter_map(Result::ok)
        .collect();
    let (definitions, unreferenced) =
        super::infer_gate::collect_defs_and_unrefs(tmp.path(), &py_parsed, &rs_parsed);
    let floor =
        super::infer_gate::compute_min_per_file_test_coverage(tmp.path(), &py_parsed, &rs_parsed);
    let gate = infer_gate_config_for_paths(&paths, None, &ignore);
    assert_eq!(
        gate.test_coverage_threshold, floor,
        "inferred threshold should equal computed floor"
    );
    let map = crate::cli_output::file_coverage_map(&definitions, &unreferenced);
    let worst: Vec<_> = map
        .iter()
        .filter(|(p, _)| crate::cli_output::is_coverage_gate_file(p))
        .map(|(p, pct)| (p.display().to_string(), *pct))
        .collect();
    let mut worst = worst;
    worst.sort_by_key(|(_, pct)| *pct);
    if let Some((path, pct)) = worst.first() {
        assert_eq!(
            gate.test_coverage_threshold, *pct,
            "threshold should match worst gate file {path} at {pct}%"
        );
    }
}

#[test]
fn test_infer_gate_config_orphan_module_enabled() {
    let tmp = TempDir::new().unwrap();
    let orphan_py = tmp.path().join("orphan.py");
    std::fs::write(&orphan_py, "def foo():\n    pass\n").unwrap();
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    let gate = infer_gate_config_for_paths(&paths, Some(Language::Python), &[]);
    assert!(
        !gate.orphan_module_enabled,
        "orphan module should set orphan_module_enabled=false"
    );
}

#[test]
fn test_infer_gate_config_no_orphans_module_enabled() {
    let tmp = TempDir::new().unwrap();
    let a_py = tmp.path().join("a.py");
    let b_py = tmp.path().join("b.py");
    std::fs::write(&a_py, "from b import bar\ndef foo():\n    bar()\n").unwrap();
    std::fs::write(&b_py, "def bar():\n    pass\n").unwrap();
    let paths = vec![tmp.path().to_string_lossy().to_string()];
    let gate = infer_gate_config_for_paths(&paths, Some(Language::Python), &[]);
    assert!(
        gate.orphan_module_enabled,
        "no orphan modules should set orphan_module_enabled=true"
    );
}
#[test]
fn test_write_mimic_config_smoke() {
    let tmp = tempfile::tempdir().unwrap();
    let out = tmp.path().join("mimic_out.toml");
    let toml = "[gate]\ntest_coverage_threshold = 90\n";
    write_mimic_config(&out, toml, 0, 0).unwrap();
    assert!(out.exists());
}

#[test]
fn write_mimic_config_merges_existing_file_by_detected_language() {
    let tmp = tempfile::tempdir().unwrap();
    let out = tmp.path().join("mimic_out.toml");
    std::fs::write(
        &out,
        "[python]\nstatements_per_function = 3\n[rust]\narguments = 4\n[thresholds]\nbranches_per_function = 7\n",
    )
    .unwrap();
    let new_toml = "[python]\nstatements_per_function = 8\n[rust]\narguments = 9\n[shared]\nline_length = 120\n";

    write_mimic_config(&out, new_toml, 1, 0).unwrap();

    let merged = std::fs::read_to_string(&out).unwrap();
    assert!(merged.contains("statements_per_function = 8"));
    assert!(merged.contains("arguments = 4"));
    assert!(merged.contains("branches_per_function = 7"));
    assert!(merged.contains("line_length = 120"));
}

#[test]
fn test_merge_config_toml_smoke() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(&path, "[python]\nstatements_per_function = 1\n").unwrap();
    let merged = merge_config_toml(
        &path,
        "[python]\nstatements_per_function = 2\n[rust]\narguments = 4\n",
        MergeLanguageUpdate::Both,
    );
    assert!(merged.contains("statements_per_function"));
}

#[test]
fn merge_config_toml_returns_new_toml_when_inputs_do_not_parse() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(&path, "not = [valid").unwrap();

    let new_toml = "[python]\nstatements_per_function = 2\n";

    assert_eq!(
        merge_config_toml(&path, new_toml, MergeLanguageUpdate::Both),
        new_toml
    );
    std::fs::write(&path, "[python]\nstatements_per_function = 1\n").unwrap();
    assert_eq!(
        merge_config_toml(&path, "not = [valid", MergeLanguageUpdate::Both),
        "not = [valid"
    );
}

#[test]
fn merge_config_toml_updates_only_analyzed_language_sections() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(
        &path,
        "[gate]\ntest_coverage_threshold = 50\n[python]\nstatements_per_function = 1\n[rust]\narguments = 2\n[shared]\nline_length = 80\n[thresholds]\nbranches_per_function = 3\n",
    )
    .unwrap();
    let new_toml = "[gate]\ntest_coverage_threshold = 90\n[python]\nstatements_per_function = 10\n[rust]\narguments = 20\n[shared]\nline_length = 100\n";

    let py_only = merge_config_toml(&path, new_toml, MergeLanguageUpdate::PythonOnly);
    assert!(py_only.contains("test_coverage_threshold = 90"));
    assert!(py_only.contains("statements_per_function = 10"));
    assert!(py_only.contains("arguments = 2"));
    assert!(py_only.contains("line_length = 80"));
    assert!(py_only.contains("branches_per_function = 3"));

    let rust_only = merge_config_toml(&path, new_toml, MergeLanguageUpdate::RustOnly);
    assert!(rust_only.contains("statements_per_function = 1"));
    assert!(rust_only.contains("arguments = 20"));
    assert!(rust_only.contains("line_length = 80"));
    assert!(rust_only.contains("branches_per_function = 3"));

    let both = merge_config_toml(&path, new_toml, MergeLanguageUpdate::Both);
    assert!(both.contains("statements_per_function = 10"));
    assert!(both.contains("arguments = 20"));
    assert!(both.contains("line_length = 100"));
    assert!(!both.contains("branches_per_function = 3"));
}

#[test]
fn merge_config_toml_can_preserve_all_existing_language_sections() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("cfg.toml");
    std::fs::write(
        &path,
        "[python]\nstatements_per_function = 1\n[rust]\narguments = 2\n[shared]\nline_length = 80\n[thresholds]\nbranches_per_function = 3\n",
    )
    .unwrap();
    let new_toml = "[python]\nstatements_per_function = 10\n[rust]\narguments = 20\n";

    let merged = merge_config_toml(&path, new_toml, MergeLanguageUpdate::Neither);

    assert!(merged.contains("statements_per_function = 1"));
    assert!(merged.contains("arguments = 2"));
    assert!(merged.contains("line_length = 80"));
    assert!(merged.contains("branches_per_function = 3"));
}
