use std::fmt::Write;

use crate::gate_config::GateConfig;
use crate::graph::GraphKeyMaxima;
use crate::stats::{MetricStats, PercentileSummary, compute_summaries};

use super::config_keys::{python_config_key, rust_config_key};

pub struct GenerateConfigParams<'a> {
    pub py: &'a MetricStats,
    pub rs: &'a MetricStats,
    pub py_n: usize,
    pub rs_n: usize,
    pub py_graph: GraphKeyMaxima,
    pub rs_graph: GraphKeyMaxima,
    pub gate: &'a GateConfig,
}

const GRAPH_METRIC_IDS: &[&str] = &["cycle_size", "indirect_dependencies", "dependency_depth"];

fn is_graph_metric_id(metric_id: &str) -> bool {
    GRAPH_METRIC_IDS.contains(&metric_id)
}

pub fn generate_config_toml_by_language(p: &GenerateConfigParams<'_>) -> String {
    let mut out = String::from(
        "# Generated by kiss check\n# Thresholds based on max values of analyzed codebase\n\n",
    );
    let _ = writeln!(out, "[global]");
    let _ = writeln!(out, "min_similarity = {}", p.gate.min_similarity);
    let _ = writeln!(out, "duplication_enabled = {}", p.gate.duplication_enabled);
    let _ = writeln!(
        out,
        "orphan_module_enabled = {}",
        p.gate.orphan_module_enabled
    );
    let _ = writeln!(
        out,
        "comment_removal_enabled = {}",
        p.gate.comment_removal_enabled
    );
    write_toml_string_list(&mut out, "docs_allowed", &p.gate.docs_allowed);
    out.push('\n');
    let _ = writeln!(out, "[test]");
    let _ = writeln!(
        out,
        "test_coverage_threshold = {}",
        p.gate.test_coverage_threshold
    );
    let _ = writeln!(
        out,
        "test_coverage_scope = \"{}\"",
        p.gate.test_coverage_scope
    );
    let _ = writeln!(out, "max_num_tests = {}", p.gate.max_num_tests);
    let _ = writeln!(out, "num_jobs = 4");
    let _ = writeln!(out, "watch_settle_seconds = 1.0");
    let _ = writeln!(out, "pytest_plugins = []");
    let _ = writeln!(out, "ignore = []");
    let _ = write!(
        out,
        "\n{}",
        crate::gate_config::format_nested_toml_table(&p.gate.max_unit_test_seconds)
    );
    out.push('\n');
    if p.py_n > 0 {
        append_language_section(
            &mut out,
            "[python]",
            &compute_summaries(p.py),
            python_config_key,
            p.py_graph,
        );
    }
    if p.rs_n > 0 {
        append_language_section(
            &mut out,
            "[rust]",
            &compute_summaries(p.rs),
            rust_config_key,
            p.rs_graph,
        );
    }
    out
}

fn write_toml_string_list(out: &mut String, key: &str, values: &[String]) {
    if values.is_empty() {
        let _ = writeln!(out, "{key} = []");
        return;
    }
    let rendered = values
        .iter()
        .map(|p| format!("\"{p}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "{key} = [{rendered}]");
}

#[cfg(test)]
pub fn append_section(
    out: &mut String,
    header: &str,
    sums: &[PercentileSummary],
    key_fn: fn(&str) -> Option<&'static str>,
) {
    append_language_section(out, header, sums, key_fn, GraphKeyMaxima::default());
}

fn append_language_section(
    out: &mut String,
    header: &str,
    sums: &[PercentileSummary],
    key_fn: fn(&str) -> Option<&'static str>,
    graph_max: GraphKeyMaxima,
) {
    out.push_str(header);
    out.push('\n');
    for s in sums {
        if is_graph_metric_id(s.metric_id) {
            continue;
        }
        if let Some(k) = key_fn(s.metric_id) {
            let _ = writeln!(out, "{k} = {}", s.max);
        }
    }
    let _ = writeln!(
        out,
        "indirect_dependencies = {}",
        graph_max.indirect_dependencies
    );
    let _ = writeln!(out, "dependency_depth = {}", graph_max.dependency_depth);
    let _ = writeln!(out, "cycle_size = {}", graph_max.cycle_size);
    out.push('\n');
}

#[cfg(test)]
mod coverage_witness {
    use super::*;
    use crate::gate_config::GateConfig;
    use crate::stats::MetricStats;

    impl GenerateConfigParams<'_> {
        fn witness() {}
    }

    #[test]
    fn witness_generate_config_params() {
        GenerateConfigParams::witness();
        let py = MetricStats::default();
        let rs = MetricStats::default();
        let gate = GateConfig::default();
        let p = GenerateConfigParams {
            py: &py,
            rs: &rs,
            py_n: 0,
            rs_n: 0,
            py_graph: GraphKeyMaxima::default(),
            rs_graph: GraphKeyMaxima::default(),
            gate: &gate,
        };
        let toml = generate_config_toml_by_language(&p);
        assert!(toml.contains("[global]"));
        assert!(
            toml.contains("comment_removal_enabled = false"),
            "global comment_removal emission:\n{toml}"
        );
        assert!(
            toml.contains("docs_allowed = []"),
            "global docs_allowed emission:\n{toml}"
        );
        assert!(
            toml.contains(
                "test_coverage_threshold = 90\ntest_coverage_scope = \"codebase\"\nmax_num_tests = 999999\n"
            ),
            "test gate emission:\n{toml}"
        );
        assert!(
            toml.contains("[test.max_unit_test_seconds]\n\"*\" = 2\n"),
            "default asterisk mapping:\n{toml}"
        );
        assert!(toml.contains("[test]\n"), "test section present:\n{toml}");
        assert!(
            !toml.contains("[python]"),
            "zero python files must omit [python]:\n{toml}"
        );
        assert!(
            !toml.contains("[rust]"),
            "zero rust files must omit [rust]:\n{toml}"
        );
    }
}
