use std::fmt::Write;

use crate::gate_config::GateConfig;
use crate::graph::GraphKeyMaxima;
use crate::stats::{MetricStats, PercentileSummary, compute_summaries};

use super::config_keys::{python_config_key, rust_config_key};

pub struct GenerateConfigParams<'a> {
    pub py: &'a MetricStats,
    pub rs: &'a MetricStats,
    pub py_n: usize,
    pub rs_n: usize,
    pub py_graph: GraphKeyMaxima,
    pub rs_graph: GraphKeyMaxima,
    pub gate: &'a GateConfig,
}

const GRAPH_METRIC_IDS: &[&str] = &["cycle_size", "indirect_dependencies", "dependency_depth"];

fn is_graph_metric_id(metric_id: &str) -> bool {
    GRAPH_METRIC_IDS.contains(&metric_id)
}

pub fn auto_created_gate_config() -> GateConfig {
    GateConfig {
        duplication_enabled: false,
        orphan_detection: false,
        comment_removal_enabled: false,
        docs_allowed: vec!["./".to_string()],
        test_coverage_threshold: 0,
        max_unit_test_seconds: vec![("*".to_string(), 99999.0)],
        ..GateConfig::default()
    }
}

pub fn generate_config_toml_by_language(p: &GenerateConfigParams<'_>) -> String {
    let mut out = String::from(
        "# Generated by kiss check\n# Thresholds based on max values of analyzed codebase\n\n",
    );
    let _ = writeln!(out, "[global]");
    let _ = writeln!(out, "min_similarity = {}", p.gate.min_similarity);
    let _ = writeln!(out, "duplication_enabled = {}", p.gate.duplication_enabled);
    let _ = writeln!(
        out,
        "comment_removal_enabled = {}",
        p.gate.comment_removal_enabled
    );
    write_toml_string_list(&mut out, "docs_allowed", &p.gate.docs_allowed);
    write_toml_string_list(&mut out, "orphan_allowed", &p.gate.orphan_allowed);
    out.push('\n');
    let _ = writeln!(out, "[test]");
    let _ = writeln!(
        out,
        "test_coverage_threshold = {}",
        p.gate.test_coverage_threshold
    );
    let _ = writeln!(
        out,
        "test_coverage_scope = \"{}\"",
        p.gate.test_coverage_scope
    );
    let _ = writeln!(out, "orphan_detection = {}", p.gate.orphan_detection);
    let _ = writeln!(out, "max_num_tests = {}", p.gate.max_num_tests);
    let _ = writeln!(out, "num_jobs = {}", crate::defaults::gate::NUM_JOBS);
    let _ = writeln!(
        out,
        "watch_settle_seconds = {:.1}",
        crate::defaults::gate::WATCH_SETTLE_SECONDS
    );
    let _ = writeln!(out, "pytest_plugins = []");
    let _ = writeln!(out, "ignore = []");
    let _ = write!(
        out,
        "\n{}",
        crate::gate_config::format_nested_toml_table(&p.gate.max_unit_test_seconds)
    );
    out.push('\n');
    if p.py_n > 0 {
        append_language_section(
            &mut out,
            "[python]",
            &compute_summaries(p.py),
            python_config_key,
            p.py_graph,
        );
    }
    if p.rs_n > 0 {
        append_language_section(
            &mut out,
            "[rust]",
            &compute_summaries(p.rs),
            rust_config_key,
            p.rs_graph,
        );
    }
    out
}

fn write_toml_string_list(out: &mut String, key: &str, values: &[String]) {
    if values.is_empty() {
        let _ = writeln!(out, "{key} = []");
        return;
    }
    let rendered = values
        .iter()
        .map(|p| format!("\"{p}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "{key} = [{rendered}]");
}

#[cfg(test)]
pub fn append_section(
    out: &mut String,
    header: &str,
    sums: &[PercentileSummary],
    key_fn: fn(&str) -> Option<&'static str>,
) {
    append_language_section(out, header, sums, key_fn, GraphKeyMaxima::default());
}

fn append_language_section(
    out: &mut String,
    header: &str,
    sums: &[PercentileSummary],
    key_fn: fn(&str) -> Option<&'static str>,
    graph_max: GraphKeyMaxima,
) {
    out.push_str(header);
    out.push('\n');
    for s in sums {
        if is_graph_metric_id(s.metric_id) {
            continue;
        }
        if let Some(k) = key_fn(s.metric_id) {
            let _ = writeln!(out, "{k} = {}", s.max);
        }
    }
    let _ = writeln!(
        out,
        "indirect_dependencies = {}",
        graph_max.indirect_dependencies
    );
    let _ = writeln!(out, "dependency_depth = {}", graph_max.dependency_depth);
    let _ = writeln!(out, "cycle_size = {}", graph_max.cycle_size);
    out.push('\n');
}

#[cfg(test)]
mod coverage_witness {
    use super::*;
    use crate::gate_config::GateConfig;
    use crate::stats::MetricStats;

    impl GenerateConfigParams<'_> {
        fn witness() {}
    }

    #[test]
    fn auto_created_gate_disables_static_and_test_gates() {
        let gate = auto_created_gate_config();
        assert!(!gate.duplication_enabled);
        assert!(!gate.orphan_detection);
        assert!(!gate.comment_removal_enabled);
        assert_eq!(gate.docs_allowed, vec!["./".to_string()]);
        assert_eq!(gate.test_coverage_threshold, 0);
        assert_eq!(gate.max_unit_test_seconds, vec![("*".to_string(), 99999.0)]);
        let py = MetricStats::default();
        let rs = MetricStats::default();
        let toml = generate_config_toml_by_language(&GenerateConfigParams {
            py: &py,
            rs: &rs,
            py_n: 0,
            rs_n: 0,
            py_graph: GraphKeyMaxima::default(),
            rs_graph: GraphKeyMaxima::default(),
            gate: &gate,
        });
        assert!(
            toml.contains("duplication_enabled = false"),
            "auto-created global flags:\n{toml}"
        );
        assert!(
            !toml.contains("orphan_module_enabled"),
            "auto-created config must not write orphan_module_enabled:\n{toml}"
        );
        assert!(
            toml.contains("orphan_detection = false"),
            "auto-created test flags:\n{toml}"
        );
        assert!(
            toml.contains("comment_removal_enabled = false"),
            "auto-created global flags:\n{toml}"
        );
        assert!(
            toml.contains(r#"docs_allowed = ["./"]"#),
            "auto-created docs_allowed:\n{toml}"
        );
        assert!(
            toml.contains("orphan_allowed = []"),
            "auto-created orphan_allowed:\n{toml}"
        );
        assert!(
            toml.contains("test_coverage_threshold = 0\n"),
            "auto-created coverage:\n{toml}"
        );
        assert!(
            toml.contains("[test.max_unit_test_seconds]\n\"*\" = 99999\n"),
            "auto-created unit-test seconds:\n{toml}"
        );
    }

    #[test]
    fn witness_generate_config_params() {
        GenerateConfigParams::witness();
        let py = MetricStats::default();
        let rs = MetricStats::default();
        let gate = GateConfig::default();
        let p = GenerateConfigParams {
            py: &py,
            rs: &rs,
            py_n: 0,
            rs_n: 0,
            py_graph: GraphKeyMaxima::default(),
            rs_graph: GraphKeyMaxima::default(),
            gate: &gate,
        };
        let toml = generate_config_toml_by_language(&p);
        assert!(toml.contains("[global]"));
        assert!(
            toml.contains("comment_removal_enabled = false"),
            "global comment_removal emission:\n{toml}"
        );
        assert!(
            toml.contains("docs_allowed = []"),
            "global docs_allowed emission:\n{toml}"
        );
        assert!(
            toml.contains("orphan_allowed = []"),
            "global orphan_allowed emission:\n{toml}"
        );
        assert!(
            toml.contains(
                "test_coverage_threshold = 90\ntest_coverage_scope = \"codebase\"\norphan_detection = false\nmax_num_tests = 999999\n"
            ),
            "test gate emission:\n{toml}"
        );
        assert!(
            toml.contains("[test.max_unit_test_seconds]\n\"*\" = 2\n"),
            "default asterisk mapping:\n{toml}"
        );
        assert!(toml.contains("[test]\n"), "test section present:\n{toml}");
        assert!(
            !toml.contains("[python]"),
            "zero python files must omit [python]:\n{toml}"
        );
        assert!(
            !toml.contains("[rust]"),
            "zero rust files must omit [rust]:\n{toml}"
        );
    }
}
