use std::path::Path;

pub fn format_section(out: &mut String, name: &str, section: Option<&toml::Value>) {
    use std::fmt::Write;
    if let Some(v) = section {
        let _ = writeln!(out, "[{name}]");
        if let Some(t) = v.as_table() {
            for (k, v) in t {
                let _ = writeln!(out, "{k} = {v}");
            }
        }
        out.push('\n');
    }
}

/// Which language sections to take from the newly generated TOML when merging.
#[derive(Clone, Copy)]
pub enum MergeLanguageUpdate {
    PythonOnly,
    RustOnly,
    Both,
    Neither,
}

impl MergeLanguageUpdate {
    pub const fn from_analyzed_counts(py_cnt: usize, rs_cnt: usize) -> Self {
        match (py_cnt > 0, rs_cnt > 0) {
            (true, true) => Self::Both,
            (true, false) => Self::PythonOnly,
            (false, true) => Self::RustOnly,
            (false, false) => Self::Neither,
        }
    }

    const fn update_python(self) -> bool {
        matches!(self, Self::PythonOnly | Self::Both)
    }

    const fn update_rust(self) -> bool {
        matches!(self, Self::RustOnly | Self::Both)
    }

    const fn update_both(self) -> bool {
        matches!(self, Self::Both)
    }
}

pub fn merge_config_toml(path: &Path, new: &str, lang: MergeLanguageUpdate) -> String {
    let Some((ex, nw)) = load_merge_tables(path, new) else {
        return new.to_string();
    };
    let mut merged = toml::Table::new();
    merge_gate(&mut merged, &ex, &nw);
    merge_lang_sections(&mut merged, &ex, &nw, lang);
    merge_shared(&mut merged, &ex, &nw, lang);
    merge_thresholds(&mut merged, &ex, lang);
    build_merged_output(&merged)
}

pub(super) fn load_merge_tables(path: &Path, new: &str) -> Option<(toml::Table, toml::Table)> {
    let ex_str = std::fs::read_to_string(path).ok()?;
    let ex = ex_str.parse::<toml::Table>().ok()?;
    let nw = new.parse::<toml::Table>().ok()?;
    Some((ex, nw))
}

pub(super) fn merge_gate(merged: &mut toml::Table, ex: &toml::Table, nw: &toml::Table) {
    if let Some(v) = nw.get("gate").cloned().or_else(|| ex.get("gate").cloned()) {
        merged.insert("gate".to_string(), v);
    }
}

pub(super) fn merge_lang_sections(
    merged: &mut toml::Table,
    ex: &toml::Table,
    nw: &toml::Table,
    lang: MergeLanguageUpdate,
) {
    let pick = |k: &str, upd: bool| if upd { nw.get(k) } else { ex.get(k) }.cloned();
    for (k, upd) in [
        ("python", lang.update_python()),
        ("rust", lang.update_rust()),
    ] {
        if let Some(v) = pick(k, upd) {
            merged.insert(k.to_string(), v);
        }
    }
}

pub(super) fn merge_shared(
    merged: &mut toml::Table,
    ex: &toml::Table,
    nw: &toml::Table,
    lang: MergeLanguageUpdate,
) {
    let shared = if lang.update_both() {
        nw.get("shared")
    } else {
        ex.get("shared").or_else(|| nw.get("shared"))
    }
    .cloned();
    if let Some(v) = shared {
        merged.insert("shared".to_string(), v);
    }
}

pub(super) fn merge_thresholds(
    merged: &mut toml::Table,
    ex: &toml::Table,
    lang: MergeLanguageUpdate,
) {
    if !lang.update_both()
        && let Some(v) = ex.get("thresholds").cloned()
    {
        merged.insert("thresholds".to_string(), v);
    }
}

pub fn build_merged_output(m: &toml::Table) -> String {
    let mut out = String::from(
        "# Generated by kiss mimic\n# Thresholds based on max values of analyzed codebase\n\n",
    );
    for k in ["gate", "python", "rust", "shared", "thresholds"] {
        format_section(&mut out, k, m.get(k));
    }
    out
}
