pub const THRESHOLDS_KEYS: &[&str] = &[
    "statements_per_function",
    "methods_per_class",
    "statements_per_file",
    "lines_per_file",
    "functions_per_file",
    "arguments_per_function",
    "arguments_positional",
    "arguments_keyword_only",
    "max_indentation_depth",
    "interface_types_per_file",
    "concrete_types_per_file",
    // Back-compat: older configs used classes_per_file for types-per-file.
    "classes_per_file",
    "nested_function_depth",
    "returns_per_function",
    "return_values_per_function",
    "branches_per_function",
    "local_variables_per_function",
    "imported_names_per_file",
    "statements_per_try_block",
    "boolean_parameters",
    "annotations_per_function",
    "calls_per_function",
    "cycle_size",
    "indirect_dependencies",
    "dependency_depth",
];

pub const SHARED_KEYS: &[&str] = &[
    "statements_per_file",
    "lines_per_file",
    "functions_per_file",
    "interface_types_per_file",
    "concrete_types_per_file",
    // Back-compat: older configs used types_per_file for concrete types.
    "types_per_file",
    "imported_names_per_file",
    "cycle_size",
    "indirect_dependencies",
    "dependency_depth",
];

pub const PYTHON_KEYS: &[&str] = &[
    "statements_per_function",
    "positional_args",
    "keyword_only_args",
    "max_indentation",
    "branches_per_function",
    "local_variables",
    "methods_per_class",
    "returns_per_function",
    "return_values_per_function",
    "nested_function_depth",
    "statements_per_try_block",
    "boolean_parameters",
    "decorators_per_function",
    "calls_per_function",
    "imported_names_per_file",
    "statements_per_file",
    "lines_per_file",
    "functions_per_file",
    "interface_types_per_file",
    "concrete_types_per_file",
    // Back-compat alias.
    "types_per_file",
    "cycle_size",
    "indirect_dependencies",
    "dependency_depth",
];

pub const RUST_KEYS: &[&str] = &[
    "statements_per_function",
    "arguments",
    "max_indentation",
    "branches_per_function",
    "local_variables",
    "methods_per_class",
    "statements_per_file",
    "lines_per_file",
    "functions_per_file",
    "interface_types_per_file",
    "concrete_types_per_file",
    // Back-compat alias.
    "types_per_file",
    "returns_per_function",
    "nested_function_depth",
    "boolean_parameters",
    "attributes_per_function",
    "calls_per_function",
    "imported_names_per_file",
    "cycle_size",
    "indirect_dependencies",
    "dependency_depth",
];
