use std::fmt::Write;

use super::percentile::PercentileSummary;

pub fn format_stats_table(summaries: &[PercentileSummary]) -> String {
    let header = format!(
        "{:<28} {:>5} {:>5} {:>5} {:>5} {:>5} {:>5}",
        "metric_id", "N", "p50", "p90", "p95", "p99", "max"
    );
    let mut out = header;
    out.push('\n');
    out.push_str(&"-".repeat(out.trim_end_matches('\n').len()));
    out.push('\n');
    for s in summaries.iter().filter(|s| s.count > 0) {
        let _ = writeln!(
            out,
            "{:<28} {:>5} {:>5} {:>5} {:>5} {:>5} {:>5}",
            s.metric_id, s.count, s.p50, s.p90, s.p95, s.p99, s.max
        );
    }
    out
}

/// Map `metric_id` to config key (some metrics use different config key names)
pub(crate) fn config_key_for(metric_id: &str) -> Option<&'static str> {
    Some(match metric_id {
        "statements_per_function" => "statements_per_function",
        "arguments_per_function" => "arguments_per_function",
        "positional_args" => "arguments_positional",
        "keyword_only_args" => "arguments_keyword_only",
        "max_indentation_depth" => "max_indentation_depth",
        "nested_function_depth" => "nested_function_depth",
        "returns_per_function" => "returns_per_function",
        "return_values_per_function" => "return_values_per_function",
        "branches_per_function" => "branches_per_function",
        "local_variables_per_function" => "local_variables_per_function",
        "statements_per_try_block" => "statements_per_try_block",
        "boolean_parameters" => "boolean_parameters",
        "annotations_per_function" => "annotations_per_function",
        "calls_per_function" => "calls_per_function",
        "methods_per_class" => "methods_per_class",
        "statements_per_file" => "statements_per_file",
        "lines_per_file" => "lines_per_file",
        "functions_per_file" => "functions_per_file",
        "interface_types_per_file" => "interface_types_per_file",
        "concrete_types_per_file" => "concrete_types_per_file",
        "imported_names_per_file" => "imported_names_per_file",
        "fan_in" => "fan_in",
        "fan_out" => "fan_out",
        "cycle_size" => "cycle_size",
        "indirect_dependencies" => "indirect_dependencies",
        "dependency_depth" => "dependency_depth",
        _ => return None,
    })
}

pub fn generate_config_toml(summaries: &[PercentileSummary]) -> String {
    let mut out = String::from(
        "# Generated by kiss mimic\n# Thresholds based on 99th percentile\n\n[thresholds]\n",
    );
    for s in summaries {
        if let Some(k) = config_key_for(s.metric_id) {
            let _ = writeln!(out, "{k} = {}", s.p99);
        }
    }
    out
}
