#[derive(Debug, Clone)]
pub struct UnitMetrics {
    pub file: String,
    pub name: String,
    pub kind: &'static str,
    pub line: usize,
    pub statements: Option<usize>,
    pub arguments: Option<usize>,
    pub args_positional: Option<usize>,
    pub args_keyword_only: Option<usize>,
    pub indentation: Option<usize>,
    pub nested_depth: Option<usize>,
    pub branches: Option<usize>,
    pub returns: Option<usize>,
    pub return_values: Option<usize>,
    pub locals: Option<usize>,
    pub methods: Option<usize>,
    pub lines: Option<usize>,
    pub imports: Option<usize>,
    pub fan_in: Option<usize>,
    pub fan_out: Option<usize>,
    pub indirect_deps: Option<usize>,
    pub dependency_depth: Option<usize>,
}
